site_name: 'Plex 使用者指南'
site_description: 'A Material Design theme for MkDocs'
site_author: 'Joshua Avalon'
#site_url: 'https://squidfunk.github.io/mkdocs-material/'

theme:
  name: 'material'
  logo: 'img/icon.png'
  font: false
  favicon: 'img/favicon.ico'
  language: 'zh-Hant'

extra:
  search:
    language: 'en, jp'

extra_css:
  - 'css/extra.min.css'

copyright: 'Copyright &copy; 2017 - 2017 Joshua Avalon'

markdown_extensions:
  - admonition

pages:
  - 簡介: index.md
  - 網頁版: web.md
  - Android: android.md
  - iOS: ios.md